name: HoloItems
version: 3.0.0
author: klin
main: com.klin.holoItems.HoloItems
api-version: 1.17
commands:
  collections:
    usage: /<command>
  worldname:
    usage: /<command>
  custommodeldata:
    usage: /<command>
  acquire:
    usage: /<command> <id>
  registry:
    usage: /<command>
  disable:
    usage: /<command> <id>
  enable:
    usage: /<command> <id>
  collect:
    usage: /<command> <stat> <type> <id>
  gethead:
    usage: /<command> <name>
  setcustommodeldata:
    usage: /<command> <custommodeldata>
  settype:
    usage: /<command> <type>
  removechunktickets:
    usage: /<command>
  test:
    usage: /<command>